version: "3.7"

services:

  bblog-web:
    image: registry.cn-shenzhen.aliyuncs.com/blockchain101/bblog-web
    ports:
      - "8080:8080"
    depends_on:
      - bblog-api

  bblog-api:
    image: registry.cn-shenzhen.aliyuncs.com/blockchain101/bblog-api
    depends_on:
    - bblog-db
    - bblog-sol

  bblog-db:
    image: registry.cn-shenzhen.aliyuncs.com/blockchain101/bblog-mysql

  bblog-eth:
    image: registry.cn-shenzhen.aliyuncs.com/blockchain101/bblog-eth

    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"

  bblog-ipfs:
    image: registry.cn-shenzhen.aliyuncs.com/blockchain101/bblog-ipfs

  bblog-sol:
    build: ./contracts
    depends_on:
      - bblog-eth