version: "3.7"

services:

  bblog-web:
    build:
      context: ./src/web
    ports:
      - "8080:8080"
    env_file:
      - ./src/base.env
      - ./src/contracts.env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - bblog-api

  bblog-api:
    build:
      context: ./src/server/api
    ports:
      - "5000:5000"
    env_file:
    - ./src/base.env
    - ./src/contracts.env
    deploy:
      replicas: 2
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
    - bblog-db
    - bblog-sol


  bblog-eth:
    build:
      context: ./src/server/eth
    networks:
      -
    ports:
      - "8545:8545"
      - "30303:30303"
      - "30303:30303/udp"
    env_file:
    - ./src/base.env
    - ./src/contracts.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        delay: 10s
      restart_policy:
        condition: on-failure

  bblog-ipfs:
    build:
      context: ./src/server/ipfs
    ports:
      - "4001:4001"
      - "5001:5001"
      - "8080:8080"
      - "8081:8081"
    env_file:
    - ./src/base.env
    - ./src/contracts.env
    deploy:
      replicas: 1
      update_config:
        parallelism: 0
        delay: 10s
      restart_policy:
        condition: on-failure

  bblog-sol:
    build:
      context: ./src/server/sol/contracts
    depends_on:
      - bblog-eth

networks:
  bblog-frontend:
  bblog-backend: