# @Time     : 2020/4/5 1:41 PM
# @Author   : TaibiaoGuo
# @Github   : https://github.com/TaibiaoGuo
# @Describe : Developers compile bblog with this script. If you encounter a network failure while building, You must
#             set up a network proxy or docker registry proxy to successfully run this script.

version: "3.7"

services:

  bblog-web:
    build:
      context: ./src/web
    ports:
      - "${WEB_PORT}:8080"
    env_file:
      - ./src/base.env
      - ./src/contracts.env
    deploy:
      endpoint_mode: vip
    depends_on:
      - bblog-api

  bblog-api:
    build:
      context: ./src/server/api
    ports:
      - "${API_PORT}:5000"
    env_file:
    - ./src/base.env
    - ./src/contracts.env
    depends_on:
    - bblog-db
    - bblog-sol


  bblog-eth:
    build:
      context: ./src/server/eth
    ports:
      - "${ETH_RPC_PORT}:8545"
      - "${ETH_P2P_PORT}:30303"
      - "${ETH_P2P_PORT}:30303/udp"
    env_file:
    - ./src/base.env
    - ./src/contracts.env

  bblog-ipfs:
    build:
      context: ./src/server/ipfs
    ports:
      - "${IPFS_P2P_PORT}:4001"
      - "${IPFS_API_PORT}:5001"
      - "${IPFS_GATEWAY_PORT}:8080"
      - "${IPFS_WEBSOCKET_PORT}:8081"
    env_file:
    - ./src/base.env
    - ./src/contracts.env

  bblog-sol:
    build: ./contracts
    depends_on:
      - bblog-eth