name: ci-bblog-geth

          on:
            push:
              paths:
              - src/server/eth
              branches:
              - master

          jobs:
            build-deploy:
              runs-on: ubuntu-18.04
              steps:
              - uses: actions/checkout@v1

